var websites = {
    "Bizarre Propagation":"bizarrepropagation",
    "Blackhat Post":"blackhatpost",
    "Blushing Brides":"blushingbrides",
    "Building a Future":"buildingafuture",
    "Cavity Lease":"cavitylease",
    "Chevron":"chevron",
    "Crisis Calls":"crisiscalls",
    "Crystal Guild":"crystalguild",
    "Doctor Murder":"doctormurder",
    "Don't waste it":"dontwasteit",
    "Doughy":"doughy",
    "Drug tickets":"drugtickets",
    "Eat My Shit":"ems",
    "Encrave":"encrave",
    "Final Standing":"finalstanding",
    "FindLove":"findlove",
    "Forever Friend":"foreverfriend",
    "Forsaken Gifts":"forsakengifts",
    "I am here":"iamhere",
    "Jakob's sink":"jakobssink",
    "Keep Sake":"keepsake",
    "Kill for me":"killforme",
    "Lab Monkey":"labmonkey",
    "Lost Tapes":"losttapes",
    "Mama Bruguglio":"mamabruguglio",
    "Mors n more market":"morsnmoremarket",
    "Oneless":"oneless",
    "Order of nine":"orderofnine",
    "Overnight Success":"overnightsuccess",
    "Prohibited Stockpile":"prohibitedstockpile",
    "Red Handed":"redhanded",
    "Red Triangle":"redtriangle",
    "Ring Ring":"ringring",
    "Shelter":"shelter",
    "Symphoros Chosen":"symphoroschosen",
    "Synapse Decay":"synapsedecay",
    "Tango Down":"tangodown",
    "Thanks for Visiting":"thanksforvisting",
    "The Bomb Maker":"thebombmaker",
    "The Grey":"TheGrey",
    "The Hall":"thehall",
    "The Hole":"thehole",
    "The Light Within":"thelightwithin",
    "The Loogaroo":"theloogaroo",
    "The Prey":"theprey",
    "Time Sharing":"timesharing",
    "Track06":"track06",
    "ViaMarisRoute":"viamarisroute",
    "Voluvision":"voluvision",
    "World Wide Workers":"worldwideworkers",
    "You There?":"youthere",
}

const FIRSTQUARTER = 0
const SECONDQUARTER = 1
const THIRDQUARTER = 2
const FOURTHQUARTER = 3
const FIRSTHALF = 4
const SECONDHALF = 5
const ALWAYS = 6

var websiteUpTimes = {
    "bizarrepropagation":THIRDQUARTER,
    "blackhatpost":FIRSTHALF,
    "blushingbrides":ALWAYS,
    "buildingafuture":SECONDQUARTER,
    "cavitylease":ALWAYS,
    "chevron":SECONDHALF,
    "crisiscalls":ALWAYS,
    "crystalguild":THIRDQUARTER,
    "doctormurder":ALWAYS,
    "dontwasteit":ALWAYS,
    "doughy":ALWAYS,
    "drugtickets":FIRSTHALF,
    "ems":SECONDQUARTER,
    "encrave":ALWAYS,
    "finalstanding":SECONDHALF,
    "findlove":FIRSTQUARTER,
    "foreverfriend":ALWAYS,
    "forsakengifts":FIRSTQUARTER,
    "iamhere":THIRDQUARTER,
    "jakobssink":ALWAYS,
    "keepsake":THIRDQUARTER,
    "killforme":FIRSTHALF,
    "labmonkey":SECONDHALF,
    "losttapes":ALWAYS,
    "mamabruguglio":FIRSTHALF,
    "morsnmoremarket":FIRSTQUARTER,
    "oneless":ALWAYS,
    "orderofnine":FIRSTQUARTER,
    "overnightsuccess":SECONDQUARTER,
    "prohibitedstockpile":ALWAYS,
    "redhanded":FIRSTHALF,
    "redtriangle":ALWAYS,
    "ringring":ALWAYS,
    "shelter":THIRDQUARTER,
    "symphoroschosen":ALWAYS,
    "synapsedecay":ALWAYS,
    "tangodown":ALWAYS,
    "thanksforvisting":ALWAYS,
    "thebombmaker":ALWAYS,
    "TheGrey":SECONDHALF,
    "thehall":FOURTHQUARTER,
    "thehole":ALWAYS,
    "thelightwithin":ALWAYS,
    "theloogaroo":ALWAYS,
    "theprey":FIRSTQUARTER,
    "timesharing":ALWAYS,
    "track06":ALWAYS,
    "viamarisroute":FIRSTHALF,
    "voluvision":ALWAYS,
    "worldwideworkers":ALWAYS,
    "youthere":THIRDQUARTER,
}

var websiteSubPages = {
    "bizarrepropagation":["index"],
    "blackhatpost":["index", "submit"],
    "blushingbrides":["index", "join", "samples"],
    "buildingafuture":["index", "invest"],
    "cavitylease":["index", "submit"],
    "chevron":["index"],
    "crisiscalls":["index", "account", "resetpassword"],
    "crystalguild":["index", "welcome"],
    "doctormurder":["index"],
    "dontwasteit":["index", "no", "holdit", "yes"],
    "doughy":["index"],
    "drugtickets":["index", "checkout", "error"],
    "ems":["index", "faq", "questions", "secret"],
    "encrave":["index", "gateopen", "evident"],
    "finalstanding":["index"],
    "findlove":["index"],
    "foreverfriend":["index", "order"],
    "forsakengifts":["index", "gifts", "order"],
    "iamhere":["index"],
    "jakobssink":["index"],
    "keepsake":["index", "thesearch", "contact"],
    "killforme":["index", "targets", "instructions"],
    "labmonkey":["index", "catalog", "sign-in", "error"],
    "losttapes":["index", "page2", "purchase"],
    "mamabruguglio":["index"],
    "morsnmoremarket":["index", "menu", "order", "ordersent"],
    "oneless":["index"],
    "orderofnine":["index", "join"],
    "overnightsuccess":["index", "purchase"],
    "prohibitedstockpile":["index", "nocontent"],
    "redhanded":["index", "login", "post1", "post2", "post4", "post6"],
    "redtriangle":["index"],
    "ringring":["index", "answer"],
    "shelter":["index", "donate", "events"],
    "symphoroschosen":["index", "sendlinks", "live"],
    "synapsedecay":["index", "myfriends", "getmoney", "succulentmeal", "occasionally"],
    "tangodown":["index", "payment", "results", "hire"],
    "thanksforvisting":["index", "bar", "connected", "creepy", "fakemain", "jolly", "plug", "portal", "sleeptalk", "slide2", "smile", "ulike", "vision"],
    "thebombmaker":["index"],
    "TheGrey":["index", "interius", "latus", "centrum", "inanis"],
    "thehall":["index"],
    "thehole":["index"],
    "thelightwithin":["index", "saved"],
    "theloogaroo":["index", "locations"],
    "theprey":["index"],
    "timesharing":["index", "packages", "watch"],
    "track06":["index"],
    "viamarisroute":["index", "secondpage", "thirdpage", "order"],
    "voluvision":["index", "testimonials", "purchase"],
    "worldwideworkers":["index", "about", "submit"],
    "youthere":["index"],
}